### ISSUE TITLE
Make the panel with the simulation history moveable/collapsable

### ISSUE THREAD

**Issue by mgieseking** [adamtool/webinterface#106]
In the simulation panel the window with the simulation history can be in the way of the Petri net. Since we can move the Petri net around, this is not such a big deal, but it would still be a nice feature to at least make the panel collapsable or even allow for moving it around.

**Comment by annyanich** [comment]
I just made another commit to refine the behavior some more.  Now it shrinks down to a little circle with an eyeball just like the tool picker sidebar when it is hidden.
