### ISSUE TITLE
SYNT: Increase the default values of the physics control for the 2-player game and strategy

### ISSUE THREAD

**Issue by mgieseking** [adamtool/webinterface#107]
The default values for the physics control for the two-player game and the strategy are too small. This leads to a too dense visualization of the nodes. We should increase the default values to have a less cluttered view.

**Comment by annyanich** [comment]
Ok, I played around with a few examples and ended up increasing both repulsion and link strength by a factor of 2 or 3, and it seems to behave well with the examples I tried.  I also raised the maximum values of the physics sliders to give a little bit more room for experimentation.  Let me know if you run into any examples that are still hard to read with the newly tuned parameters.
