### ISSUE TITLE
Modify build process to work offline from a tarball on a newly installed debian machine

### ISSUE THREAD

**Issue by annyanich** [adamtool/webinterface#59]
I will see to it that there is a script which can run offline from a single tarball to build and run the server and client.

- Find debian packages or other means to install maven, node, npm
- Convert maven deps, both plugins and libraries, into offline deps (can one possibly just copy the .m2 folder from my dev machine?)
- Put a copy of node_modules with all dependencies inside
- Modify pom.xml to use the pre-installed node, npm and node_modules

**Comment by mgieseking** [comment]
I think if it is possible that we get it already compiled on the VM, put this binary files in the tar-ball, such that the reviewer can only use ./run.sh, to run the server, this would also be fine and could make the process way easier @annyanich ?

**Comment by annyanich** [comment]
Ah, hmmm!!  Yes, now that you mention it, the artifact evaluation guidelines do not say you have to compile it in the vm :D  
Yes this will be way easier.  We just have to make sure the dependencies aiger, mchyper, abc are there and the 'time' and 'dot' packages are installed.

**Comment by annyanich** [comment]
I am having a look now into getting the VM up and running on my laptop.  Unfortunately I am having some difficulties importing the "ova" file into virtualbox, I keep getting this error:

`
Progress state: NS_ERROR_INVALID_ARG
VBoxManage: error: Appliance import failed
VBoxManage: error: Code NS_ERROR_INVALID_ARG (0x80070057) - Invalid argument value (extended info not available)
VBoxManage: error: Context: "RTEXITCODE handleImportAppliance(HandlerArg*)" at line 1118 of file VBoxManageAppliance.cpp
`
I get almost the same error in virtubalbox 6.1 or 6.0.  I\m about to try 5.2 because that is also packaged for debian 10.  You haven't tried doing this yet by any chance, have you?

**Comment by mgieseking** [comment]
OK, so when you think it is possible that I just clone this repo in the VM, set-up mchyper, abc, and all the dependencies, build it as usual and can take this folder as the artifact to ship it to another instance of this VM, and the user can then only use the run.sh, then I can try to do so, since at least for abc and mchyper I did it already for the other artifacts. Currently, I also have a problem running the VM.

**Comment by annyanich** [comment]
Yup, sounds good ^^  
BTW the command 'vboxmanage import TACAS\ 21.ova' gave me a different error on Virtualbox 5.2:

`
Progress state: VBOX_E_FILE_ERROR
VBoxManage: error: Appliance import failed
VBoxManage: error: Could not create the imported medium '/home/ann/VirtualBox VMs/TACAS 21/TACAS 21-disk001.vmdk'.
VBoxManage: error: VMDK: Compressed image is corrupted '/home/ann/TACAS 21-disk001.vmdk' (VERR_ZIP_CORRUPTED)
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component ApplianceWrap, interface IAppliance
VBoxManage: error: Context: "RTEXITCODE handleImportAppliance(HandlerArg*)" at line 886 of file VBoxManageAppliance.cpp
`

I am not sure if this means the image really is corrupted or if it's just Virtualbox's inability to handle certain vmdk files.  I would suggest trying VMWare if you are also using Virtualbox.  It says here it can be installed on Debian Buster and Stretch without problems: https://wiki.debian.org/VMware#VMware_Workstation_Pro.2FPlayer_15.2F15.5
The vmware player is free for non-commercial use: https://www.vmware.com/de/products/workstation-player/workstation-player-evaluation.html

**Comment by annyanich** [comment]
I just re-downloaded the OVA file and it seems to work now.  I think the download must have been corrupted the first time.  I actually had a lot of trouble downloading it in Firefox from the page, it kept saying "download failed" after it finished.... If you want, I can upload the OVA to homer for you to download from there, since I think their download page may not be completely reliable.  @mgieseking

**Comment by annyanich** [comment]
(I checked the md5sum of the newly downloaded file and it matches the one on the official download page, 69a669e532c77eccb637a7b8c93988a4.  My previously downloaded one had a bad MD5, 35cc7a330a97c10b9135dd67f52f66d8.)

**Comment by mgieseking** [comment]
No it's fine for me. The VM is working for me, but thanks.

**Comment by mgieseking** [comment]
OK, so for a binary version I now have already compiled every dependency and the server for this virtual machine and downloaded the needed packages so that we only have to exchange the final binary of the server.

If you want you may have a look if it works for you as expected:
https://cloudstorage.elearning.uni-oldenburg.de/s/DJFZNHWSko4j7NS

If there is time at the end, we can also create the large artifact with all the dependencies to also compile the current version of the web interface. Thus, I just leave it open for now.
