### ISSUE TITLE
Allow saving model checking net as pnml

### ISSUE THREAD

**Issue by annyanich** [adamtool/webinterface#65]
For the model checking net it would also be good to have save as pnml

_Originally posted by @mgieseking in https://github.com/adamtool/webinterface/issues/23#issuecomment-706096814_

**Comment by annyanich** [comment]
I think you should make the method static.  To call it now, I have to do `new Adam().pn2pnml(net); ` because I do not have an Adam instance hanging around.  So for now, I will just do PNTools.pn2pnml(net), if that's ok.

**Comment by mgieseking** [comment]
Yes, perfect you are right. It's fine just leave it by this method (even though the methods are now static and come with the next commit)

**Comment by annyanich** [comment]
All rightie

**Comment by mgieseking** [comment]
I thought there had been an issue also for the synthesis, but I don't find it. So for the strategy there should also be the option to save it to PNML and also for the input Petri game.

**Comment by annyanich** [comment]
Ok, I added it in 11eb3faca39c7bf4da335b774d69d30272541302 :)
