### ISSUE TITLE
Improvements of the menu bar

### ISSUE THREAD

**Issue by mgieseking** [adamtool/webinterface#75]
There are some ideas to improve the bar:

- that the menu bar takes the complete width
- the name of the tool complete to the left (if possible with a separator | ) that draws more attention
- when there are children the item has an arrow (one could just use the ascii sign I guess ▼)
- a link to the github page
- having a help button leading to the documentation
- a home button
- then I would move help, github, about, home in this order to the right

**Comment by annyanich** [comment]
I like what you did here, it makes it a bit closer to the standard Material Design web app UI when the bar stretches across the whole screen.

I had a look at implementing your 3 ideas:

- I think it will be difficult to make the middle item unselectable.  The library I made the menu with seems not to be made with that use case in mind.  If I had a lot of time on my hands, I could monkey patch it, but I probably won't get to it before we turn in the artifact.

- Putting icons in the menu items also seems to be quite difficult without patching the library.  The text is strictly a string; see the line `{{label}}` in this file https://github.com/michitaro/vue-menu/blob/master/src/menubaritem/index.vue.  We would have to patch the DOM to insert a SVG element there instead.

- I did lower the main content :) in d87e6de34ee5ededb4a1d58e10b03070ad2716b3

**Comment by mgieseking** [comment]
>     * I think it will be difficult to make the middle item unselectable.  The library I made the menu with seems not to be made with that use case in mind.  If I had a lot of time on my hands, I could monkey patch it, but I probably won't get to it before we turn in the artifact.

OK, this sounds intricate, but would it be possible to change the css for hover over, so that it don't changes the color ;)?

**Comment by annyanich** [comment]
U are right, I did it :)  thanks for the idea

**Comment by annyanich** [comment]
Possibly with CSS tricks I can do the github icon as well, but I will save that for later.
