### ISSUE TITLE
Add a help dialog

### ISSUE THREAD

**Issue by mgieseking** [adamtool/webinterface#78]
In the menu bar add a help item (see #75) with 
- short cuts -> opening a panel as for about with the shortcuts (see #35 )
- syntax (im MC part) -> opening a panel as for about with a table of the syntax of the logics
- link to video and or pdf what ever is there as docu

**Comment by annyanich** [comment]
Ok, I have made a "help" modal with shortcuts and a place to put the MC syntax.  Can you provide me with an appropriate text to show the mc syntax?  (HTML would be great)

**Comment by mgieseking** [comment]
The header should be Flow-LTL syntax.

The syntax for **Flow-LTL** is given by:

```
phi =  LTL   |   ( phi AND phi )   |   ( phi OR phi )   |   ( LTL -> phi )   |   A LTL
```

with standard LTL formulas with the following operators:

| LTL         | Syntax      |
| ----------- | ----------- |
| true     | TRUE    |
| false    | FALSE    |
| atoms     | place and transition ids    |
| Negation    | NEG or !    |
| Next    | X   |
| Conjunction | AND         |
| Disjunction | OR         |
| Implication | IMP or ->         |
| Bimplication| BIMP or <->         |
| Until | U         |
| Weak Until | W         |
| Release | R         |

Binary operators have to be in brackets, unary operators not. For example (!phi0 -> (phi1 AND G F phi2)). Note that the ids for the places and transitions are more restricted for the formula as for the web interface.

**Comment by annyanich** [comment]
Nice, thanks :)

**Comment by annyanich** [comment]
I put the formula syntax and a link to the github documentation in there.  Can you check it out and close the issue if this works for you?
![2020-10-22-185919_1193x941](https://user-images.githubusercontent.com/19911087/96905438-b9386f00-1498-11eb-9f43-7603c528232e.png)

**Comment by annyanich** [comment]
The user guide link takes you to the one corresponding to the mode you are in (mc or synt).

**Comment by mgieseking** [comment]
Currently I don't see the user guide in the synt case? But otherwise everything is good.

**Comment by annyanich** [comment]
Ah, thanks :) I have unhidden it in 4b7f4d78faed786f3146b72638f3f9999cc0de2a
