### ISSUE TITLE
Upgrade to new versions of junit and axios

### ISSUE THREAD

**Issue by mgieseking** [adamtool/webinterface#84]
Is it possible to upgrade to the new versions such that these problems are fixed? https://github.com/adamtool/webinterface/network/alerts

**Comment by annyanich** [comment]
I can't seem to see the alerts, can you send me a screenshot?

**Comment by mgieseking** [comment]
I have this on the code page:
![start](https://user-images.githubusercontent.com/4051993/96720380-f7effb80-13aa-11eb-8360-f874a0031ac1.png)

and this then in the security tab:
![details](https://user-images.githubusercontent.com/4051993/96720389-faeaec00-13aa-11eb-9ec8-2911e21e013e.png)

You cannot see this? Because in the security tab there are details to that (roughly just to update to a new version ;))

**Comment by annyanich** [comment]
Ah, nope, I can't see either of those things -- I can even go to the security tab, but the dependabot alerts are not shown.  I will have a look into upgrading both of those.

**Comment by annyanich** [comment]
Fixed as of 624f4250b44cf97e70b36da68d4679c0d2656e52
