### ISSUE TITLE
Refine the simulator for use with counter examples

### ISSUE THREAD

**Issue by annyanich** [adamtool/webinterface#86]
For a lot of nets, a user would really benefit from being able to see the tokens travel and the transitions be fired as they step through a counter example, I think, because otherwise there is no visual feedback when you click around in the history as long as the number of tokens at all places remains constant.  

I would like to try out:
- Flash the transitions that fired between the current history state and the one you click on
- Show an animation of tokens flying around between Places
- Add a "Fire next" button / hotkey to allow stepping through the history firing-by-firing.

**Comment by mgieseking** [comment]
I think to have a fast visual feedback by just flashing the transition one have clicked (as for normal firing) would already be good so that one checks that s.th. happens and the web interface is working.
