### ISSUE TITLE
MC: 'Show Data Flow' for the counter example creates the wrong pdf

### ISSUE THREAD

**Issue by mgieseking** [adamtool/webinterface#87]
The button 'SHOW DATA FLOW' in the tab for the counter example (not the simulation) should call the method MCTools::saveDataFlowWitnessToPDF(String path, PetriNetWithTransits pnwt, ReducedCounterExample detailedCEX, String procID) throws FileNotFoundException, IOException {
    
where pnwt is the input PetriNetWithTransits and detailedCEX is the detailed version of the reduced counter example.

This method did not exist before, see #68 .

Better relabel the button also to SHOW WITNESSES

**Comment by annyanich** [comment]
I'm sorry, to be sure, "detailed cex" refers to the ReducedCounterExample I create here,r ight?

![2020-10-21-134705_943x101](https://user-images.githubusercontent.com/19911087/96715507-fa9b2280-13a3-11eb-8aa1-727fc3fea5db.png)

**Comment by annyanich** [comment]
I put the tooltip "Download a PDF which shows the witnesses for this counter example." Is that correct?

**Comment by mgieseking** [comment]
> I'm sorry, to be sure, "detailed cex" refers to the ReducedCounterExample I create here,r ight?

It refers to the detailed one. So called with true and with mcNet.

**Comment by annyanich** [comment]
oh!  Ok, I changed it to use that one.  
![2020-10-21-150300_1495x26](https://user-images.githubusercontent.com/19911087/96723225-93cf3680-13ae-11eb-995a-5d57b228d5dd.png)
