### ISSUE TITLE
Loading the counter examples in the editor confuses the show data flow button

### ISSUE THREAD

**Issue by mgieseking** [adamtool/webinterface#92]
When loading the extended example this is loaded and also the net is replace into the simulator to the left. Then there should no "show data flow button". On same way it worked and there wasn't the button, but when I load back a Petri net with transits, the button was still gone.

Especially the first one is a problem because this throws an exception when clicking the button.

**Comment by annyanich** [comment]
Sorry, the 'extended example' means the "counter example (constructed petri net)", right?
I will disable it for that one.

**Comment by annyanich** [comment]
>  On same way it worked and there wasn't the button, but when I load back a Petri net with transits, the button was still gone.

Is it possible that you loaded the petri net with transits from the editor?  In that case, the button will not be shown until you have fired at least one transition.

**Comment by annyanich** [comment]
Closing for now, let me know if there is anything wrong after this commit :)

**Comment by mgieseking** [comment]
Everythings fine, perfect thanks.
