### ISSUE TITLE
The position in the job queue is not printed correctly

### ISSUE THREAD

**Issue by mgieseking** [adamtool/webinterface#99]
![Screenshot from 2020-10-23 17-50-50](https://user-images.githubusercontent.com/4051993/97025788-d46ab380-1558-11eb-94bb-8e676f78cb28.png)

**Comment by annyanich** [comment]
Hmmmm, can you possibly give me a screenshot of the 'job list' the next time you see this happen?  That would help me a lot to debug this :D

**Comment by annyanich** [comment]
Never mind, I managed to reproduce it
